apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-nginxdemos-hello
  template:
    metadata:
      labels:
        app: pod-nginxdemos-hello
    spec:
      containers:
      - name: container-nginxdemos-hello
        image: nginxdemos/hello
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-clusterip
  spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80 
  selector:
    matchLabels:
    app: pod-nginxdemos-hello
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - demo-luan.tpcloud.vn
    secretName: website-tls-secret
  rules:
  - host: demo-luan.tpcloud.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-clusterip
            port:
              number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: website-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: <base64-crt>
  tls.key: <base64-key>
