apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-nginxdemos-hello
  template:
    metadata:
      labels:
        app: pod-nginxdemos-hello
    spec:
      containers:
      - name: container-nginxdemos-hello
        image: nginxdemos/hello
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: Svc-ClusterIP
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80 
  selector:
    matchLabels:
    app: pod-nginxdemos-hello
